accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

graffitie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = "profileapp"

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(AccountUpdateForm,self).__init__(*args, **kwargs)
        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorator import account_ownership_required
from accountapp.forms import AccountUpdateForm

has_ownership = [account_ownership_required,login_required]

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('home')
    template_name = 'accountapp/create.html'


# class LoginView():

# class LogoutView():

class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('home')
    template_name = 'accountapp/update.html'

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<div style="text-align: center; max-width: 400px; margin: 4rem auto">
   <form action="{% url 'accountapp:create' %}" method="post">
       {% csrf_token %}
<!--       {{ form }}-->
       {% bootstrap_form form %}

       <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
   </form>
</div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<div style="text-align: center; max-width: 400px; margin: 4rem auto">
   <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
       {% csrf_token %}
       <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="Delete ID">
   </form>
</div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<div style="text-align: center; max-width: 400px; margin: 4rem auto">
   <div>
       <p>
           {{ target_user.date_joined }}
       </p>
       {% if target_user.profile %}
       <div>
           <img src="{{ target_user.profile.image.url }}" alt="profile_image"
                class="img-responsive img-circle">
       </div>
       <h3 style="font-family:'NanumSquareR'">
           {{ target_user.profile.nickname }}
           {% if target_user == user %}
           <a class="material-icons"
              href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
               edit
           </a>
           {% endif %}
       </h3>
       <h5>
           {{ target_user.profile.message }}
       </h5>

       {% else %}
       <a href="{% url 'profileapp:create' %}">
           {% if target_user == user %}
           <h3>
           Create Profile
           </h3>
           {% endif %}
       </a>
       {% endif %}

       {% if target_user == user %}
       <a class="material-icons" href="{% url 'accountapp:update' pk=user.pk %}">
           <p>
               settings
           </p>
       </a>
       <a class="material-icons" href="{% url 'accountapp:delete' pk=user.pk %}">
           <p>
               cancel
           </p>
       </a>

       {% endif %}
   </div>
</div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<div style="text-align: center; max-width: 400px; margin: 4rem auto">
    <div>
        <h4>Login</h4>
    </div>
    <form action="" method="post">
       {% csrf_token %}
       <!--{{ form }}-->
        {% bootstrap_form form %}
       <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<div style="text-align: center; max-width: 400px; margin: 4rem auto">
   <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
       {% csrf_token %}
<!--{{ form }}-->
       {% bootstrap_form form %}
       <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
   </form>
</div>

{% endblock %}