accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = "articleapp"

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

graffitie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subscribeapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView, CommentDeleteView
from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView
from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = "subscribeapp"

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    # path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    # path('update/<int:pk>', CommentUpdateView.as_view(), name='update'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family:'NanumSquareR'">

    {% include 'header.html' %}
    <hr>
    {% block content %}
    {% endblock %}
    <hr>
    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div class="graffitie_footer">
    <div class="graffitie_footer_button">
        <span>note</span>
        <span>note</span>
        <span>note</span>
    </div>
    <div style="magin-top: 1rem">
        <span class="graffitie_footer_logo">graffitie</span>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>graffitie</title>
    <!--bootstrap link-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <!--font link-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">

    <!--css link-->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}"

    <!--fonts-->
    <style>
        @font-face{
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url('{% static 'fonts/NanumSquareR.ttf' %} format("opentype");
        }
    </style>

<!--    icon from google-->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

</head>

templates/header.html
<div class="graffitie_header">
    <div >
        <h1 class="graffitie_header_logo">graffiti</h1>
    </div>
    <div>
        <a href="{% url 'articleapp:list' %}" class="graffitie_header_nav">
            <span>Articles</span>
        </a>
        <a href="{% url 'subscribeapp:list' %}" class="graffitie_header_nav">
            <span>Subscribe</span>
        </a>
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="graffitie_header_nav">
            <span>login</span>
        </a>
        <a href="{% url 'accountapp:create' %}?next={{ request.path }}" class="graffitie_header_nav">
            <span>SignUp</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}" class="graffitie_header_nav">
            <span>MyPage</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="graffitie_header_nav">
            <span>logout</span>
        </a>
        {% endif %}
    </div>

</div>